#!/bin/bash

WORKER_FILE="parent.html"

# Находим строку </script> и вставляем функции ПЕРЕД ней
awk '
/<\/script>/ && !done {
  print ""
  print "    // ============================"
  print "    // МАГАЗИН НАГРАД"
  print "    // ============================"
  print ""
  print "    // Переключение формы создания награды"
  print "    function toggleAddRewardForm() {"
  print "      const form = document.getElementById(\"addRewardForm\");"
  print "      form.style.display = form.style.display === \"block\" ? \"none\" : \"block\";"
  print "      "
  print "      // Очистка формы при открытии"
  print "      if (form.style.display === \"block\") {"
  print "        document.getElementById(\"rewardTitle\").value = \"\";"
  print "        document.getElementById(\"rewardDescription\").value = \"\";"
  print "        document.getElementById(\"rewardPrice\").value = \"\";"
  print "        document.getElementById(\"rewardIsPermanent\").checked = false;"
  print "      }"
  print "    }"
  print ""
  print "    // Загрузка списка наград"
  print "    async function loadRewards() {"
  print "      try {"
  print "        const res = await fetch(`${API_URL}/api/rewards/list`, {"
  print "          headers: { \"X-Invite-Code\": currentCode }"
  print "        });"
  print ""
  print "        const data = await res.json();"
  print "        "
  print "        if (!Array.isArray(data.rewards)) {"
  print "          document.getElementById(\"rewardsList\").innerHTML = \"<p class=\\\"error\\\">Ошибка загрузки наград</p>\";"
  print "          return;"
  print "        }"
  print ""
  print "        const rewardsList = document.getElementById(\"rewardsList\");"
  print "        "
  print "        if (data.rewards.length === 0) {"
  print "          rewardsList.innerHTML = \"<div class=\\\"empty-state\\\">Наград пока нет. Нажмите \\'+\\' чтобы добавить.</div>\";"
  print "          return;"
  print "        }"
  print ""
  print "        rewardsList.innerHTML = data.rewards.map(reward => `"
  print "          <div class=\\\"task-item\\\" style=\\\"position: relative;\\\">"
  print "            <button class=\\\"delete-button\\\" onclick=\\\"deleteReward(\\'${reward.id}\\')\\\">✕</button>"
  print "            <div style=\\\"display: flex; align-items: center; gap: 10px;\\\">"
  print "              <span style=\\\"font-size: 32px;\\\">${reward.icon || \"🎁\"}</span>"
  print "              <div style=\\\"flex: 1;\\\">"
  print "                <strong>${reward.title}</strong>"
  print "                <div style=\\\"font-size: 14px; color: #666;\\\">${reward.description || \"\"}</div>"
  print "                <div style=\\\"margin-top: 5px;\\\">"
  print "                  <span style=\\\"font-weight: bold; color: #4CAF50;\\\">${reward.price} ⭐</span>"
  print "                  ${reward.is_permanent ? \"<span style=\\\"margin-left: 10px; font-size: 12px; color: #999;\\\">📌 Постоянный</span>\" : \"<span style=\\\"margin-left: 10px; font-size: 12px; color: #999;\\\">🔄 Разовый</span>\"}"
  print "                </div>"
  print "              </div>"
  print "            </div>"
  print "          </div>"
  print "        `).join(\"\");"
  print ""
  print "      } catch (err) {"
  print "        document.getElementById(\"rewardsList\").innerHTML = `<p class=\\\"error\\\">Ошибка: ${err.message}</p>`;"
  print "      }"
  print "    }"
  print ""
  print "    // Создание новой награды"
  print "    async function createReward() {"
  print "      const title = document.getElementById(\"rewardTitle\").value.trim();"
  print "      const description = document.getElementById(\"rewardDescription\").value.trim();"
  print "      const price = parseInt(document.getElementById(\"rewardPrice\").value);"
  print "      const isPermanent = document.getElementById(\"rewardIsPermanent\").checked;"
  print ""
  print "      // Валидация"
  print "      if (!title) {"
  print "        alert(\"Введите название награды\");"
  print "        return;"
  print "      }"
  print ""
  print "      if (!price || price < 1 || price > 10000) {"
  print "        alert(\"Цена должна быть от 1 до 10000\");"
  print "        return;"
  print "      }"
  print ""
  print "      try {"
  print "        const res = await fetch(`${API_URL}/api/rewards/create`, {"
  print "          method: \"POST\","
  print "          headers: {"
  print "            \"Content-Type\": \"application/json\","
  print "            \"X-Invite-Code\": currentCode"
  print "          },"
  print "          body: JSON.stringify({ title, description, price, is_permanent: isPermanent })"
  print "        });"
  print ""
  print "        const data = await res.json();"
  print "        "
  print "        if (data.error) {"
  print "          alert(\"Ошибка: \" + data.error);"
  print "          return;"
  print "        }"
  print ""
  print "        // Закрываем форму и обновляем список"
  print "        toggleAddRewardForm();"
  print "        loadRewards();"
  print "        "
  print "      } catch (err) {"
  print "        alert(\"Ошибка создания награды: \" + err.message);"
  print "      }"
  print "    }"
  print ""
  print "    // Удаление награды"
  print "    async function deleteReward(rewardId) {"
  print "      if (!confirm(\"Удалить эту награду?\")) {"
  print "        return;"
  print "      }"
  print ""
  print "      try {"
  print "        const res = await fetch(`${API_URL}/api/rewards/delete`, {"
  print "          method: \"DELETE\","
  print "          headers: {"
  print "            \"Content-Type\": \"application/json\","
  print "            \"X-Invite-Code\": currentCode"
  print "          },"
  print "          body: JSON.stringify({ reward_id: rewardId })"
  print "        });"
  print ""
  print "        const data = await res.json();"
  print "        "
  print "        if (data.error) {"
  print "          alert(\"Ошибка: \" + data.error);"
  print "          return;"
  print "        }"
  print ""
  print "        // Обновляем список"
  print "        loadRewards();"
  print "        "
  print "      } catch (err) {"
  print "        alert(\"Ошибка удаления награды: \" + err.message);"
  print "      }"
  print "    }"
  print ""
  done = 1
}
{ print }
' "$WORKER_FILE" > "${WORKER_FILE}.tmp"

# Заменяем файл
mv "${WORKER_FILE}.tmp" "$WORKER_FILE"

echo "✅ JavaScript функции магазина добавлены!"
echo "📊 Новый размер файла:"
wc -l "$WORKER_FILE"
