#!/bin/bash
# Патч для добавления эндпоинтов rewards в worker.js

WORKER_FILE="worker.js"
BACKUP_FILE="worker.js.backup-$(date +%Y%m%d_%H%M%S)"

# Бэкап
cp "$WORKER_FILE" "$BACKUP_FILE"
echo "✅ Создан бэкап: $BACKUP_FILE"

# Находим строку с "// 404" и вставляем эндпоинты ПЕРЕД ней
awk '
/\/\/ 404/ {
  print ""
  print "      // ============================"
  print "      // REWARDS: Управление наградами"
  print "      // ============================"
  print ""
  print "      // POST /api/rewards/init — инициализация таблицы rewards (ADMIN)"
  print "      if (path === \"/api/rewards/init\" && request.method === \"POST\") {"
  print "        try {"
  print "          // Создаём таблицу rewards"
  print "          await env.DB.prepare(`"
  print "            CREATE TABLE IF NOT EXISTS rewards ("
  print "              id TEXT PRIMARY KEY,"
  print "              family_id TEXT NOT NULL,"
  print "              title TEXT NOT NULL,"
  print "              description TEXT,"
  print "              price INTEGER NOT NULL CHECK (price >= 1 AND price <= 10000),"
  print "              icon TEXT DEFAULT \"🎁\","
  print "              is_permanent INTEGER DEFAULT 0 CHECK (is_permanent IN (0, 1)),"
  print "              is_active INTEGER DEFAULT 1 CHECK (is_active IN (0, 1)),"
  print "              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
  print "              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
  print "            )"
  print "          `).run();"
  print ""
  print "          // Создаём индексы"
  print "          await env.DB.prepare(`"
  print "            CREATE INDEX IF NOT EXISTS idx_rewards_family ON rewards(family_id)"
  print "          `).run();"
  print ""
  print "          await env.DB.prepare(`"
  print "            CREATE INDEX IF NOT EXISTS idx_rewards_active ON rewards(family_id, is_active)"
  print "          `).run();"
  print ""
  print "          return json({ message: \"Таблица rewards успешно создана\" });"
  print "        } catch (err) {"
  print "          return error(`Ошибка создания таблицы: ${err.message}`, \"DB_ERROR\", 500);"
  print "        }"
  print "      }"
  print ""
  print "      // GET /api/rewards/list — список наград семьи"
  print "      if (path === \"/api/rewards/list\" && request.method === \"GET\") {"
  print "        const inviteCode = request.headers.get(\"X-Invite-Code\");"
  print "        "
  print "        if (!inviteCode) {"
  print "          return error(\"Отсутствует заголовок X-Invite-Code\", \"NO_AUTH\", 401);"
  print "        }"
  print ""
  print "        // Проверяем родителя"
  print "        const family = await env.DB.prepare("
  print "          \"SELECT id FROM families WHERE invite_code = ?\""
  print "        ).bind(inviteCode).first();"
  print ""
  print "        if (!family) {"
  print "          return error(\"Недействительный код\", \"FORBIDDEN\", 403);"
  print "        }"
  print ""
  print "        // Получаем список наград"
  print "        const rewards = await env.DB.prepare(`"
  print "          SELECT id, family_id, title, description, price, icon, is_permanent, created_at, updated_at"
  print "          FROM rewards"
  print "          WHERE family_id = ? AND is_active = 1"
  print "          ORDER BY created_at DESC"
  print "        `).bind(family.id).all();"
  print ""
  print "        return json({ rewards: rewards.results || [] });"
  print "      }"
  print ""
  print "      // POST /api/rewards/create — создание награды (только родитель)"
  print "      if (path === \"/api/rewards/create\" && request.method === \"POST\") {"
  print "        const inviteCode = request.headers.get(\"X-Invite-Code\");"
  print "        "
  print "        if (!inviteCode) {"
  print "          return error(\"Отсутствует заголовок X-Invite-Code\", \"NO_AUTH\", 401);"
  print "        }"
  print ""
  print "        // Проверяем родителя"
  print "        const family = await env.DB.prepare("
  print "          \"SELECT id FROM families WHERE invite_code = ?\""
  print "        ).bind(inviteCode).first();"
  print ""
  print "        if (!family) {"
  print "          return error(\"Только родитель может создавать награды\", \"FORBIDDEN\", 403);"
  print "        }"
  print ""
  print "        // Парсим тело запроса"
  print "        const body = await request.json();"
  print "        const { title, description, price, icon, is_permanent } = body;"
  print ""
  print "        // Валидация"
  print "        if (!title || !price) {"
  print "          return error(\"Отсутствуют обязательные поля: title, price\", \"INVALID_DATA\", 400);"
  print "        }"
  print ""
  print "        const priceInt = parseInt(price);"
  print "        if (isNaN(priceInt) || priceInt < 1 || priceInt > 10000) {"
  print "          return error(\"Цена должна быть от 1 до 10000\", \"INVALID_DATA\", 400);"
  print "        }"
  print ""
  print "        // Генерируем ID"
  print "        const rewardId = `reward_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;"
  print ""
  print "        // Создаём награду"
  print "        await env.DB.prepare(`"
  print "          INSERT INTO rewards (id, family_id, title, description, price, icon, is_permanent, is_active, created_at, updated_at)"
  print "          VALUES (?, ?, ?, ?, ?, ?, ?, 1, datetime(\"now\"), datetime(\"now\"))"
  print "        `).bind("
  print "          rewardId,"
  print "          family.id,"
  print "          title,"
  print "          description || \"\","
  print "          priceInt,"
  print "          icon || \"🎁\","
  print "          is_permanent ? 1 : 0"
  print "        ).run();"
  print ""
  print "        return json({"
  print "          message: \"Награда создана\","
  print "          reward: {"
  print "            id: rewardId,"
  print "            title,"
  print "            price: priceInt"
  print "          }"
  print "        });"
  print "      }"
  print ""
  print "      // DELETE /api/rewards/delete — удаление награды (мягкое удаление)"
  print "      if (path === \"/api/rewards/delete\" && request.method === \"DELETE\") {"
  print "        const inviteCode = request.headers.get(\"X-Invite-Code\");"
  print "        "
  print "        if (!inviteCode) {"
  print "          return error(\"Отсутствует заголовок X-Invite-Code\", \"NO_AUTH\", 401);"
  print "        }"
  print ""
  print "        // Проверяем родителя"
  print "        const family = await env.DB.prepare("
  print "          \"SELECT id FROM families WHERE invite_code = ?\""
  print "        ).bind(inviteCode).first();"
  print ""
  print "        if (!family) {"
  print "          return error(\"Только родитель может удалять награды\", \"FORBIDDEN\", 403);"
  print "        }"
  print ""
  print "        // Парсим тело запроса"
  print "        const body = await request.json();"
  print "        const { reward_id } = body;"
  print ""
  print "        if (!reward_id) {"
  print "          return error(\"Отсутствует reward_id\", \"INVALID_DATA\", 400);"
  print "        }"
  print ""
  print "        // Проверяем, что награда принадлежит семье"
  print "        const reward = await env.DB.prepare("
  print "          \"SELECT id FROM rewards WHERE id = ? AND family_id = ?\""
  print "        ).bind(reward_id, family.id).first();"
  print ""
  print "        if (!reward) {"
  print "          return error(\"Награда не найдена\", \"NOT_FOUND\", 404);"
  print "        }"
  print ""
  print "        // Мягкое удаление"
  print "        await env.DB.prepare("
  print "          \"UPDATE rewards SET is_active = 0, updated_at = datetime('\'now\'') WHERE id = ?\""
  print "        ).bind(reward_id).run();"
  print ""
  print "        return json({ message: \"Награда удалена\" });"
  print "      }"
  print ""
}
{ print }
' "$WORKER_FILE" > "${WORKER_FILE}.tmp"

# Заменяем файл
mv "${WORKER_FILE}.tmp" "$WORKER_FILE"

echo "✅ Патч применён!"
echo "📊 Новый размер файла:"
wc -l "$WORKER_FILE"

echo ""
echo "🔍 Проверка эндпоинтов:"
grep -c "api/rewards" "$WORKER_FILE"
